## Runtime configuration for the {{ cookiecutter.package_name }} application.
##
version: '1.0'
{{cookiecutter.package_name}}:
  logging: WARN
  host: ${HOSTNAME:-0.0.0.0}
  port: ${PORT:-8888}
services:
  ## Here goes the configuration of service client-sdks 