## Runtime configuration for the {{ cookiecutter.package_name }} application.
##
version: '1.0'
main:
  logging: DEBUG
  host: ${HOSTNAME:-0.0.0.0}
  port: ${PORT:-8888}
  debug: True
services:
  ## Here goes the configuration of service client-sdks 