openapi: 3.0.0
info:
  description: API definition for {{ cookiecutter.distribution_name }} service
  version: {{ cookiecutter.version }}
  title: {{ cookiecutter.distribution_name }} API
  contact:
    name: IT'IS Foundation
    email: support@simcore.io
  license:
    name: MIT
    url: https://github.com/ITISFoundation/osparc-simcore/blob/master/LICENSE
servers:
  - url: http://{host}:{port}/{version}
    description: Development server
    variables:
      host:
        default: 'localhost'
      port:
        default: '8001'
      version:
        default: 'v{{ cookiecutter.version.split(".")[0] }}'
        enum:
          - 'v{{ cookiecutter.version.split(".")[0]}}'
tags:
- name: admins
  description: Secured Admin-only calls
- name: developers
  description: Operations available to regular developers
- name: users
  description: Operations available to regular users
paths:
  /:
    get:
      tags: 
        - users
      summary: Service health-check endpoint
      description: Some general information on the API and state of the service behind
      operationId: root_get
      responses:
        "200":
          description: Service information
          content:
            application/json:
              schema:
                $ref: 'components/schemas/health_check.yaml#HealthCheckEnveloped'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: 'components/schemas/error.yaml#ErrorEnveloped'
